//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvalusAssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Inventory
    {
        [Key]
        public int Id { get; set; }
        public string Item_Name { get; set; }
        public string Category { get; set; }
        public string Serial_Number { get; set; }
        public string QR_Code { get; set; }
        public string Date_Added { get; set; }
        public string Status { get; set; }
        public string Image { get; set; }
        public string Current_User { get; set; }
    }
}
